# Generated by Django 6.0.6 on 2026-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original name of the uploaded PDF file', max_length=255)),
                ('file', models.FileField(help_text='Uploaded PDF file', upload_to='contracts/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('counterparty_name', models.CharField(blank=True, help_text='Name of the other party in the contract', max_length=255, null=True)),
                ('contract_type', models.CharField(blank=True, help_text='Type of contract e.g. NDA, MSA, Employment', max_length=100, null=True)),
                ('governing_law', models.CharField(blank=True, help_text='Governing law jurisdiction e.g. California, India', max_length=255, null=True)),
                ('contract_start_date', models.DateField(blank=True, help_text='Contract start date', null=True)),
                ('contract_end_date', models.DateField(blank=True, help_text='Contract end date', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', help_text='Current processing status of the document', max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='Number of high-risk clauses found in the document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the document was uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the document record was last updated')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
