# Generated by Django 6.0.6 on 2026-06-08 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('confidentiality', 'Confidentiality'), ('termination', 'Termination'), ('indemnification', 'Indemnification'), ('governing_law', 'Governing Law'), ('limitation_of_liability', 'Limitation of Liability'), ('intellectual_property', 'Intellectual Property'), ('dispute_resolution', 'Dispute Resolution'), ('payment_terms', 'Payment Terms'), ('warranties', 'Warranties'), ('force_majeure', 'Force Majeure'), ('other', 'Other')], default='other', help_text='Category/type of this legal clause', max_length=50)),
                ('clause_text', models.TextField(help_text='The full text of the extracted clause')),
                ('page_number', models.PositiveIntegerField(default=1, help_text='Page number where this clause appears in the PDF')),
                ('confidence_score', models.FloatField(default=0.0, help_text='NLP confidence score between 0.0 and 1.0')),
                ('extracted_at', models.DateTimeField(auto_now_add=True, help_text='When this clause was extracted')),
                ('document', models.ForeignKey(help_text='The document this clause belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.document')),
            ],
            options={
                'verbose_name': 'Extracted Clause',
                'verbose_name_plural': 'Extracted Clauses',
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_title', models.CharField(help_text="Short title of the risk e.g. 'Unlimited Liability Found'", max_length=255)),
                ('flagged_text', models.TextField(help_text='The exact text that was flagged as risky')),
                ('keyword_matched', models.CharField(blank=True, help_text='The risk keyword that triggered this flag', max_length=100, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Severity level of this risk', max_length=10)),
                ('page_number', models.PositiveIntegerField(default=1, help_text='Page number where the risk was found')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of why this clause is considered risky', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this risk has been reviewed and resolved')),
                ('flagged_at', models.DateTimeField(auto_now_add=True, help_text='When this risk was flagged')),
                ('document', models.ForeignKey(help_text='The document this risk flag belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='contracts.document')),
            ],
            options={
                'verbose_name': 'Risk Flag',
                'verbose_name_plural': 'Risk Flags',
                'ordering': ['-severity', 'page_number'],
            },
        ),
    ]
