# Generated by Django 6.0.6 on 2026-06-16 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_extractedclause_riskflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded PDF file', null=True, upload_to='contracts/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='governing_law',
            field=models.CharField(blank=True, help_text='Governing law jurisdiction', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Number of high-risk clauses found'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', help_text='Current processing status', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the document was last updated'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the document was uploaded'),
        ),
        migrations.AlterField(
            model_name='extractedclause',
            name='clause_type',
            field=models.CharField(choices=[('confidentiality', 'Confidentiality'), ('termination', 'Termination'), ('indemnification', 'Indemnification'), ('governing_law', 'Governing Law'), ('limitation_of_liability', 'Limitation of Liability'), ('intellectual_property', 'Intellectual Property'), ('dispute_resolution', 'Dispute Resolution'), ('payment_terms', 'Payment Terms'), ('warranties', 'Warranties'), ('force_majeure', 'Force Majeure'), ('other', 'Other')], db_index=True, default='other', help_text='Category of this legal clause', max_length=50),
        ),
        migrations.AlterField(
            model_name='extractedclause',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='NLP confidence score 0.0 to 1.0'),
        ),
        migrations.AlterField(
            model_name='extractedclause',
            name='page_number',
            field=models.PositiveIntegerField(default=1, help_text='Page number in the PDF'),
        ),
        migrations.AlterField(
            model_name='riskflag',
            name='document',
            field=models.ForeignKey(help_text='The document this risk belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='contracts.document'),
        ),
        migrations.AlterField(
            model_name='riskflag',
            name='explanation',
            field=models.TextField(blank=True, help_text='Why this clause is risky', null=True),
        ),
        migrations.AlterField(
            model_name='riskflag',
            name='flagged_text',
            field=models.TextField(help_text='The exact text that was flagged'),
        ),
        migrations.AlterField(
            model_name='riskflag',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this risk has been reviewed'),
        ),
        migrations.AlterField(
            model_name='riskflag',
            name='keyword_matched',
            field=models.CharField(blank=True, help_text='The keyword that triggered this flag', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='riskflag',
            name='page_number',
            field=models.PositiveIntegerField(default=1, help_text='Page number in the PDF'),
        ),
        migrations.AlterField(
            model_name='riskflag',
            name='risk_title',
            field=models.CharField(help_text='Short title of the risk', max_length=255),
        ),
        migrations.AlterField(
            model_name='riskflag',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', help_text='Severity level', max_length=10),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='contracts_d_status_2eeb64_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-uploaded_at'], name='contracts_d_uploade_0d160e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['contract_type'], name='contracts_d_contrac_771051_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedclause',
            index=models.Index(fields=['document', 'clause_type'], name='contracts_e_documen_77a4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedclause',
            index=models.Index(fields=['clause_type'], name='contracts_e_clause__0cabfb_idx'),
        ),
        migrations.AddIndex(
            model_name='riskflag',
            index=models.Index(fields=['document', 'severity'], name='contracts_r_documen_351e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='riskflag',
            index=models.Index(fields=['severity'], name='contracts_r_severit_61e2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='riskflag',
            index=models.Index(fields=['is_resolved'], name='contracts_r_is_reso_422a18_idx'),
        ),
    ]
